name: 🧪 Cypress Tests on Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: ✅ Rodar testes Cypress no Chrome
        run: npx cypress run --browser chrome

      - name: 📤 Upload de vídeos e screenshots (em caso de erro)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
